# Generated by Django 6.0.8 on 2026-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Iranian Rial'), ('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=10),
        ),
    ]
