events {}

http {
    server {
        listen 80;

        location /ws/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_pass http://web:8000;
        }

        location / {
            proxy_set_header Host $host;
            proxy_pass http://web:8000;
        }
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/ledgercore-localhost.crt;
        ssl_certificate_key /etc/nginx/ssl/ledgercore.key;

        location /ws/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_pass http://web:8000;
        }

        location / {
            proxy_set_header Host $host;
            proxy_pass http://web:8000;
        }
    }
}