# Generated by Django 6.0.8 on 2026-08-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=4)),
                ('quote_currency', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=4)),
                ('rate', models.DecimalField(decimal_places=12, max_digits=30)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'fetched_at'), name='unique_exchange_rate_snapshot')],
            },
        ),
    ]
