# Generated by Django 6.0.8 on 2026-08-25 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
