# Generated by Django 6.0.8 on 2026-08-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_exchangerate_fetched_at'),
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('destination_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee_currency', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USDT', 'Tether'), ('BTC', 'Bitcoin'), ('USD', 'US Dollar'), ('EUR', 'Euro')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_transactions', to='exchange.exchangerate')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_details', to='transactions.transaction')),
            ],
        ),
    ]
